default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "P@ssw0rd" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") { "good_night_development" } %>
test:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") { "good_night_test" } %>
production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") { "good_night_production" } %>
